// This code is generated by GenerateAst.cs. Do not modify it directly.
namespace Lox;

public abstract class Stmt {
    public interface IVisitor<T> {
        T VisitBlockStmt(Block stmt);
        T VisitExpressionStmt(Expression stmt);
        T VisitPrintStmt(Print stmt);
        T VisitVarStmt(Var stmt);
    }
    public class Block : Stmt {
        public List<Stmt?> Statements { get; private set; }

        public Block(List<Stmt?> statements) {
            Statements = statements;
        }

        public override T Accept<T>(IVisitor<T> visitor) {
            return visitor.VisitBlockStmt(this);
        }
    }
    public class Expression : Stmt {
        public Expr Expr { get; private set; }

        public Expression(Expr expr) {
            Expr = expr;
        }

        public override T Accept<T>(IVisitor<T> visitor) {
            return visitor.VisitExpressionStmt(this);
        }
    }
    public class Print : Stmt {
        public Expr Expr { get; private set; }

        public Print(Expr expr) {
            Expr = expr;
        }

        public override T Accept<T>(IVisitor<T> visitor) {
            return visitor.VisitPrintStmt(this);
        }
    }
    public class Var : Stmt {
        public Token Name { get; private set; }
        public Expr? Initializer { get; private set; }

        public Var(Token name, Expr? initializer) {
            Name = name;
            Initializer = initializer;
        }

        public override T Accept<T>(IVisitor<T> visitor) {
            return visitor.VisitVarStmt(this);
        }
    }

    public abstract T Accept<T>(IVisitor<T> visitor);
}
